
title: Joshuadesir.life
description: >- 


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

social: 
 - name: Email
   link: i@joshuadesir.life
 - name: Instagram
   link: https://instagram.com/joshuadesir

plugins:
  - jekyll-feed
