title: Joshuadesir.life
description: >-
  My awesome graphic design portfolio & personal blog; enjoy!

mainStyles: /assets/styles/main.css

social:
  email: i@joshuaddesir.com
  twitter: 
    link: https://twitter.com/
    awesomeIcon: fa-twitter
    username: joshuaddesir
  github: 
    link: https://github.com/
    awesomeIcon: fa-github
    username: joshuaddesir
  instagram: 
    link: https://twitter.com/
    awesomeIcon: fa-instagram
    username: joshuaddesir



plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll_version_plugin
  - jekyll-contentblocks
  - liquid-md5
  - jekyll-mentions
  - jekyll-default-layout
